version: "3"

volumes:
  node_modules:

services:
  gocloud_api:
    container_name: service_gocloud_api_local
    restart: "no"
    command: "npm run start"
    build:
      context: ./gocloud_api
      dockerfile: ./docker/dockerfile
    environment:
      - USE_DOCKER=yes
    env_file:
      - ./gocloud_api/env/.env-local
    volumes:
      - ./gocloud_api/app:/usr/src/app
    ports:
      - "8080:3000"

  gocloud_app:
    container_name: gocloud_app
    command: "npm run start"
    build:
      context: ./gocloud_app
      dockerfile: ./docker/dockerfile
    env_file:
      - ./gocloud_app/env/.env
    ports:
      - "3030:3000"
